### ISSUE TITLE
OLD SDK Compatability

### ISSUE THREAD

**Issue by SandeepCarnera** [StonlyHQ/stonly-ios-sdk#1]
Hi Team,
I have used StonlySdk Pod library in my iOS native, recently when i tried to install the pod, i got an issue like repo url is not found.
And also i tried with new library stonly-ios-sdk, but what ever the APIs that I used with old pod are not available.Please check this for your side.
What could be the compatible version?

**Comment by Bkh84** [comment]
Hello.
Thanks for your continuous interest on Stonly.
We no longer have a support for our previous SDK.
You should be able to use every Apis you had before and more with the new SDK, with really simple changes in your code.
Can you please contact [support@stonly.com](mailto:support@stonly.com), they will reach out to you to activate the new mobile experience on Stonly for your account and guide you on how to make the changes.
