### ISSUE TITLE
SPM Installation ?

### ISSUE THREAD

**Issue by jgodonQobuz** [StonlyHQ/stonly-ios-sdk#2]
Hi 👋 !

We'd like to test the integration of your SDK in our iOS app...

- First of all, the iOS SDK link on your [SDK installation guide](https://stonly.com/guide/en/sdk-installation-Xdh7ADFYOs/Steps/2001617,2345719,1878785,2187541,2187540) goes directly to Android SDK GitHub repo 😅

- But then I've found it in your iOS Github repo... and here we are: there is no SPM (Swift Package Manager) way available to install it... only an oldschool cocapods podspec...

Do you plan to make possible to install your SDK via SPM ?

We would be able to test it, because honestly, Cocoapods is not an option in 2023...

Thanks for your answer 

Best regards

Jeremie

**Comment by Bkh84** [comment]
Stonly is available since a couple of month on SPM
